### ISSUE TITLE
Source Map Support Disabled

### ISSUE THREAD

**Issue by dids-reyes** [farhanlabib/k6-faker-load-testing#1]
I encountered an error when attempting to import and execute the load test.

![Screenshot 2024-02-08 at 1 23 00 PM](https://github.com/farhanlabib/k6-faker-load-testing/assets/48916955/f4e8aa4b-bdda-4f58-b73f-ea74bad75e6a)
```
The source for `https://cdnjs.cloudfare.com/ajax/libs/Faker/3.1.0/faker.min.js` needs to go through babel but is over 256000 bytes. For performance reasons source map support will be disabled for this particular file.

ERRO[0001] SyntaxError: https://cdnjs.cloudfare.com/ajax/libs/Faker/3.1.0/faker.min.js: Unexpected token (1:0)
```

**Comment by farhanlabib** [comment]
Could you please share the code? I'm not getting any error.

**Comment by dids-reyes** [comment]
Sorry i forgot to close this issue the problem was on my side, its working properly thanks.
